services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: ollatair/counterapp:v1.0.0
    ports: 
      - 3002:3002
    environment:
      - PORTS=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  bookapp:
    image: ollatair/book:v1.0.0
    ports: 
      - 3000:3000
    environment:
      - PORTS=3000
    depends_on:
      - counter